"""
Legacy compatibility namespace for forkit-core.

`forkit.*` is the canonical public namespace. `forkit_core.*` remains available
in v0.1.x as a compatibility layer for existing imports.
"""

from forkit import (
    _PYDANTIC_AVAILABLE,
    AgentArchitecture,
    AgentCapabilities,
    AgentPassport,
    AgentRole,
    AgentTaskType,
    Architecture,
    BasePassport,
    CreatorInfo,
    EdgeType,
    ForkitClient,
    HashEngine,
    LicenseType,
    LineageEdge,
    LineageGraph,
    LineageNode,
    LocalRegistry,
    MemoryType,
    Modality,
    ModelCapabilities,
    ModelPassport,
    NodeType,
    PassportStatus,
    RemoteSyncBridge,
    ServerSettings,
    SystemPromptRecord,
    TaskType,
    ToolRef,
    TrainingDataRef,
    __version__,
    create_app,
    hash_engine,
)

__all__ = [
    "__version__",
    "_PYDANTIC_AVAILABLE",
    "BasePassport",
    "CreatorInfo",
    "LicenseType",
    "PassportStatus",
    "ModelPassport",
    "ModelCapabilities",
    "TrainingDataRef",
    "Architecture",
    "Modality",
    "TaskType",
    "AgentPassport",
    "AgentCapabilities",
    "AgentRole",
    "AgentTaskType",
    "AgentArchitecture",
    "MemoryType",
    "SystemPromptRecord",
    "ToolRef",
    "HashEngine",
    "hash_engine",
    "LineageGraph",
    "LineageNode",
    "LineageEdge",
    "NodeType",
    "EdgeType",
    "LocalRegistry",
    "ForkitClient",
    "RemoteSyncBridge",
    "ServerSettings",
    "create_app",
]
